import pandas as pd
from modules.ml_common import get_config_id

configs = [
    {
        "batch_size": 6,
        "early_stop_patience": 100,
        "early_stop_threshold": 0.00001,
        "imputation_strategy": "median",
        "k_folds": 5,
        "loss_name": "medae",
        "lr_factor": 0.1,
        "lr_init": 0.001,
        "lr_patience": 25,
        "lr_threshold": 0.001,
        "max_epochs": 9999,
        "model.activation_func": "elu",
        "model.dropout": 0.0,
        "model.hidden_edges": "[32, 16, 1, 2, 8, 4]",
        "model.input_dim": 1000,
        "model.model_class": "DeepMAgeModel",
        "normalization_strategy": "per_site",
        "predictor_class": "DeepMAgePredictor",
        "remove_nan_samples_perc_2": 80,
        "split_train_test_by_percent": False,
        "test_ratio": 0.2,
        "weight_decay": 0.000013
    },
    {
        "batch_size": 4,
        "early_stop_patience": 100,
        "early_stop_threshold": 0.00001,
        "imputation_strategy": "median",
        "k_folds": 5,
        "loss_name": "medae",
        "lr_factor": 0.1,
        "lr_init": 0.001,
        "lr_patience": 25,
        "lr_threshold": 0.001,
        "max_epochs": 9999,
        "model.activation_func": "elu",
        "model.dropout": 0.0,
        "model.hidden_edges": "[32, 16, 1, 2, 8, 4]",
        "model.input_dim": 1000,
        "model.model_class": "DeepMAgeModel",
        "normalization_strategy": "per_site",
        "predictor_class": "DeepMAgePredictor",
        "remove_nan_samples_perc_2": 80,
        "split_train_test_by_percent": False,
        "test_ratio": 0.2,
        "weight_decay": 0.000013
    },
    {
        "batch_size": 8,
        "early_stop_patience": 100,
        "early_stop_threshold": 0.00001,
        "imputation_strategy": "median",
        "k_folds": 5,
        "loss_name": "medae",
        "lr_factor": 0.1,
        "lr_init": 0.001,
        "lr_patience": 25,
        "lr_threshold": 0.001,
        "max_epochs": 9999,
        "model.activation_func": "elu",
        "model.dropout": 0.0,
        "model.hidden_edges": "[32, 16, 1, 2, 8, 4]",
        "model.input_dim": 1000,
        "model.model_class": "DeepMAgeModel",
        "normalization_strategy": "per_site",
        "predictor_class": "DeepMAgePredictor",
        "remove_nan_samples_perc_2": 80,
        "split_train_test_by_percent": False,
        "test_ratio": 0.2,
        "weight_decay": 0.000013
    },
    {
        "batch_size": 8,
        "early_stop_patience": 100,
        "early_stop_threshold": 0.00001,
        "imputation_strategy": "median",
        "k_folds": 5,
        "loss_name": "medae",
        "lr_factor": 0.1,
        "lr_init": 0.001,
        "lr_patience": 25,
        "lr_threshold": 0.001,
        "max_epochs": 9999,
        "model.activation_func": "elu",
        "model.dropout": 0.0,
        "model.inner_layers": "[32, 16, 1, 2, 8, 4]",
        "model.input_dim": 1000,
        "model.model_class": "DeepMAgeModel",
        "normalization_strategy": "per_site",
        "predictor_class": "DeepMAgePredictor",
        "remove_nan_samples_perc_2": 80,
        "split_train_test_by_percent": False,
        "test_ratio": 0.2,
        "weight_decay": 0.000013
    },
    {
        "batch_size": 8,
        "early_stop_patience": 100,
        "early_stop_threshold": 0.0001,
        "imputation_strategy": "median",
        "k_folds": 5,
        "loss_name": "medae",
        "lr_factor": 0.1,
        "lr_init": 0.001,
        "lr_patience": 25,
        "lr_threshold": 0.001,
        "max_epochs": 9999,
        "model.activation_func": "elu",
        "model.dropout": 0.0,
        "model.inner_layers": "[32, 16, 1, 2, 8, 4]",
        "model.input_dim": 1000,
        "model.model_class": "DeepMAgeModel",
        "normalization_strategy": "per_site",
        "predictor_class": "DeepMAgePredictor",
        "remove_nan_samples_perc_2": 80,
        "split_train_test_by_percent": False,
        "test_ratio": 0.2,
        "weight_decay": 0.000013
    },
    {
        "batch_size": 8,
        "early_stop_patience": 100,
        "early_stop_threshold": 0.0001,
        "imputation_strategy": "median",
        "k_folds": 5,
        "loss_name": "medae",
        "lr_factor": 0.1,
        "lr_init": 0.001,
        "lr_patience": 25,
        "lr_threshold": 0.001,
        "max_epochs": 9999,
        "model.activation_func": "elu",
        "model.dropout": 0.0,
        "model.inner_layers": "[32, 16, 4, 8]",
        "model.input_dim": 1000,
        "model.model_class": "DeepMAgeModel",
        "normalization_strategy": "per_site",
        "predictor_class": "DeepMAgePredictor",
        "remove_nan_samples_perc_2": 80,
        "split_train_test_by_percent": False,
        "test_ratio": 0.2,
        "weight_decay": 0.000013
    },
    {
        "batch_size": 8,
        "early_stop_patience": 100,
        "early_stop_threshold": 0.00001,
        "imputation_strategy": "median",
        "k_folds": 5,
        "loss_name": "medae",
        "lr_factor": 0.1,
        "lr_init": 0.001,
        "lr_patience": 25,
        "lr_threshold": 0.001,
        "max_epochs": 9999,
        "model.activation_func": "elu",
        "model.dropout": 0.0,
        "model.inner_layers": "[32, 16, 4, 8]",
        "model.input_dim": 1000,
        "model.model_class": "DeepMAgeModel",
        "normalization_strategy": "per_site",
        "predictor_class": "DeepMAgePredictor",
        "remove_nan_samples_perc_2": 80,
        "split_train_test_by_percent": False,
        "test_ratio": 0.2,
        "weight_decay": 0.000013
    },
    {
        "batch_size": 8,
        "early_stop_patience": 100,
        "early_stop_threshold": 0.0001,
        "imputation_strategy": "median",
        "k_folds": 5,
        "loss_name": "medae",
        "lr_factor": 0.1,
        "lr_init": 0.001,
        "lr_patience": 25,
        "lr_threshold": 0.001,
        "max_epochs": 999,
        "model.activation_func": "elu",
        "model.dropout": 0.0,
        "model.inner_layers": "[32]",
        "model.input_dim": 1000,
        "model.model_class": "DeepMAgeModel",
        "normalization_strategy": "per_site",
        "predictor_class": "DeepMAgePredictor",
        "remove_nan_samples_perc_2": 80,
        "split_train_test_by_percent": False,
        "test_ratio": 0.2,
        "weight_decay": 0.000013
    }
]

config_ids = sorted(set([get_config_id(config) for config in configs]))

df = pd.DataFrame(configs)

fjdkfdjkdfk = 1


# TODO delete this file.
